import {AppData,Category,ProjectStatus,EnquiryStatus,TeamMember} from './types';
const img=(t:string,c1='06b6d4',c2='7c3aed')=>`data:image/svg+xml;utf8,${encodeURIComponent(`<svg xmlns='http://www.w3.org/2000/svg' width='1200' height='800'><defs><linearGradient id='g' x1='0' x2='1' y1='0' y2='1'><stop stop-color='#${c1}'/><stop offset='1' stop-color='#${c2}'/></linearGradient></defs><rect fill='#070b1a' width='100%' height='100%'/><circle cx='220' cy='160' r='260' fill='url(#g)' opacity='.55'/><circle cx='980' cy='650' r='310' fill='#22c55e' opacity='.25'/><rect x='80' y='90' width='1040' height='620' rx='48' fill='rgba(255,255,255,.08)' stroke='rgba(255,255,255,.28)'/><text x='110' y='430' font-family='Arial' font-size='72' font-weight='800' fill='white'>${t}</text></svg>`)}`;
const projects=['SwasthyaQ AI','Quick Bharat','SnackPilot AI','Attendly','Manpreet Educoder','MongoDB Campus Campaign','BBAU Counselling Poster','Personal Portfolio'];
const cats:Category[]=['Websites','App UI/UX','Websites','App UI/UX','Websites','Social Media Creatives','Posters','Branding'];
export const workflow:ProjectStatus[]=['Draft','Enquiry','Quotation Sent','Approved','In Progress','Review','Changes Requested','Delivered','Archived'];
export const enquiryFlow:EnquiryStatus[]=['New Enquiry','Enquiry Review','Quotation Sent','Client Approved','Project Created','Project In Progress','Client Review','Changes Requested','Final Delivery','Completed'];
const emptySocials={linkedin:'',github:'',instagram:'',facebook:'',twitter:'',youtube:'',behance:'',dribbble:'',website:'',portfolio:'',whatsapp:'',email:'',resume:''};
const blankTeamMember=(m:any={},i=0):TeamMember=>({id:m.id||crypto.randomUUID(),username:m.username||String(m.name||m.fullName||m.full_name||'team-member').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,''),photo:m.photo||m.profile_photo_url||'',name:m.name||m.fullName||m.full_name||'',fullName:m.fullName||m.name||m.full_name||'',role:m.role||'',bio:m.bio||m.shortBio||m.short_bio||'',shortBio:m.shortBio||m.bio||m.short_bio||'',longBio:m.longBio||m.long_bio||m.bio||'',skills:Array.isArray(m.skills)?m.skills:[],experience:m.experience||'',location:m.location||'',email:m.email||'',phone:m.phone||'',socials:{...emptySocials,...(m.socials||{})},projects:Array.isArray(m.projects)?m.projects:[],active:m.active??m.is_visible??true,featured:m.featured??m.is_featured??false,order:Number(m.order??m.display_order??i+1),joinDate:m.joinDate||m.join_date||'',availability:m.availability||m.availability_status||'Available',resumeUrl:m.resumeUrl||m.resume_url||''});
export const demoData:AppData={projects:projects.map((p,i)=>({id:crypto.randomUUID(),title:p,category:cats[i],coverImage:img(p,i%2?'2563eb':'06b6d4',i%3?'7c3aed':'0ea5e9'),galleryImages:[img(p+' 01'),img(p+' 02','9333ea','0284c7')],clientName:i>4?'Demo Campaign':'Internal / Demo',year:2026,description:`A polished creative case study for ${p}, ready to edit from the admin dashboard.`,problem:'The brand needed a sharper digital presence that communicates value quickly and looks premium on every screen.',process:'Discovery, moodboard, wireframes, visual design, revisions, responsive polish and publishing checklist.',result:'Delivered a modern creator-studio look with strong hierarchy, clear calls to action and reusable visual assets.',tools:['Figma','Photoshop','React','Canva'].slice(0,2+i%3),tags:[p.split(' ')[0].toLowerCase(),'design',cats[i].toLowerCase()],link:'https://example.com',featured:i<4,published:i!==5,status:(i<2?'Delivered':i<5?'In Progress':'Draft') as ProjectStatus,order:i+1,revenue:[18000,12000,22000,9000,15000,5000,3500,8000][i],deadline:`2026-0${(i%6)+2}-15`,updates:[{date:'2026-01-05',status:'Enquiry',note:'Requirement collected'},{date:'2026-01-10',status:'Approved',note:'Visual direction approved'}]})),services:['Website Design','App UI/UX','Thumbnail Design','Poster Design','Branding','Website Maintenance'].map((n,i)=>({id:crypto.randomUUID(),name:n,icon:['MonitorSmartphone','PanelsTopLeft','Youtube','Image','Sparkles','Wrench'][i],description:`Premium ${n.toLowerCase()} service for growing local brands with conversion-focused creative direction.`,price:['Rs. 8,999','Rs. 6,999','Rs. 799','Rs. 999','Rs. 4,999','Rs. 1,999/mo'][i],deliveryTime:['5-10 days','4-8 days','24-48 hours','1-2 days','3-6 days','Monthly'][i],deliverables:['Strategy','Editable source','Export files','Revision support'].slice(0,3+i%2),active:true,order:i+1})),team:[],enquiries:[],content:[{id:crypto.randomUUID(),title:'Festival campaign creative',type:'Campaign creatives',caption:'Premium festive launch artwork for local business growth.',hashtags:['#Branding','#Design'],status:'Idea',image:img('Content Idea'),dueDate:'2026-08-20'}],settings:{businessName:'EduCoder Coding Hub',logo:'ECH',ownerName:'Manpreet Singh',ownerProfile:'Owner and creative lead',email:'hello@educodercodinghub.com',phone:'+91 90000 00000',whatsapp:'https://wa.me/919000000000',socials:{instagram:'',linkedin:'',github:'',youtube:''},theme:'dark',currency:'INR',defaultProjectStatus:'Draft',notifications:true,paymentLink:'',upiId:'',paymentMerchant:'EduCoder Coding Hub',paymentQrUrl:''},notifications:[],activity:['EduCoder Coding Hub demo data installed','Portfolio starter projects added']};
export const STORAGE_KEY='mch_data_v1'; export const AUTH_KEY='mch_admin_auth';
function normalizeMember(m:any,i:number):TeamMember{const member=blankTeamMember(m,i);member.socials.email=member.socials.email||member.email||'';member.socials.resume=member.socials.resume||member.resumeUrl||'';return member}
export function loadData():AppData{try{const raw=localStorage.getItem(STORAGE_KEY); const d:AppData=raw?JSON.parse(raw):demoData;d.settings={...demoData.settings,...d.settings,businessName:'EduCoder Coding Hub',logo:d.settings?.logo==='MCH'?'ECH':(d.settings?.logo||'ECH')};d.team=(d.team||[]).map(normalizeMember);return d}catch{return demoData}}
export function saveData(d:AppData){localStorage.setItem(STORAGE_KEY,JSON.stringify(d))}
