export type Category='Websites'|'App UI/UX'|'YouTube Thumbnails'|'Posters'|'Social Media Creatives'|'Branding';
export type ProjectStatus='Draft'|'Enquiry'|'Quotation Sent'|'Approved'|'In Progress'|'Review'|'Changes Requested'|'Delivered'|'Archived';
export type EnquiryStatus='New Enquiry'|'Enquiry Review'|'Quotation Sent'|'Client Approved'|'Project Created'|'Project In Progress'|'Client Review'|'Changes Requested'|'Final Delivery'|'Completed';
export type ContentStatus='Idea'|'In Design'|'Review'|'Approved'|'Published';
export type AvailabilityStatus='Available'|'Busy'|'On Leave'|'Not Available';
export interface Project{ id:string; title:string; category:Category; coverImage:string; galleryImages:string[]; clientName:string; year:number; description:string; problem:string; process:string; result:string; tools:string[]; tags:string[]; link:string; featured:boolean; published:boolean; status:ProjectStatus; order:number; assignedTo?:string; revenue:number; deadline?:string; updates:{date:string;status:string;note:string}[] }
export interface Service{ id:string; name:string; icon:string; description:string; price:string; deliveryTime:string; deliverables:string[]; active:boolean; order:number }
export interface SocialLinks{linkedin:string;github:string;instagram:string;facebook:string;twitter:string;youtube:string;behance:string;dribbble:string;website:string;portfolio:string;whatsapp:string;email:string;resume:string}
export interface TeamMember{ id:string; username:string; photo:string; name:string; fullName:string; role:string; bio:string; shortBio:string; longBio:string; skills:string[]; experience:string; location:string; email:string; phone:string; socials:SocialLinks; projects:string[]; active:boolean; featured:boolean; order:number; joinDate:string; availability:AvailabilityStatus; resumeUrl:string }
export interface Enquiry{ id:string; number:string; name:string; email:string; phone:string; business:string; service:string; budget:string; deadline:string; description:string; file?:string; status:EnquiryStatus; notes:string[]; assignedTo?:string; createdAt:string; paymentAmount?:number; paymentStatus?:'Unpaid'|'Payment Started'|'Paid'; paymentRef?:string }
export interface ContentItem{ id:string; title:string; type:string; caption:string; hashtags:string[]; status:ContentStatus; image:string; dueDate:string }
export interface Settings{ businessName:string; logo:string; ownerName:string; ownerProfile:string; email:string; phone:string; whatsapp:string; socials:{instagram:string;linkedin:string;github:string;youtube:string}; theme:'dark'|'light'; currency:string; defaultProjectStatus:ProjectStatus; notifications:boolean; paymentLink?:string; upiId?:string; paymentMerchant?:string; paymentQrUrl?:string }
export interface AppData{ projects:Project[]; services:Service[]; team:TeamMember[]; enquiries:Enquiry[]; content:ContentItem[]; settings:Settings; notifications:{id:string;message:string;date:string;read:boolean}[]; activity:string[] }
